services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./script:/scripts
    working_dir: /scripts
    environment:
      - SCRIPT=register.js
    command: run --summary-export=summary.json $SCRIPT
    network_mode: host